const postMockData = [
    {
        username: "alice123",
        title: "New Album Release",
        description: "Excited for the new album release from my favorite artist!",
        spotify_link: "",
        image_url: "https://example.com/image1.jpg",
        likes_list: ["bobsmith", "charlieb", "dianam", "evag"],
        dislikes_list: ["frankl", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "bobsmith",
        title: "Concert Experience",
        description: "Had an amazing time at the concert last night!",
        spotify_link: "",
        image_url: "https://example.com/image2.jpg",
        likes_list: ["alice123", "charlieb", "dianam", "evag"],
        dislikes_list: ["gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "charlieb",
        title: "Music Festival Highlights",
        description: "Recapping the best moments from the music festival!",
        spotify_link: "",
        image_url: "https://example.com/image3.jpg",
        likes_list: ["dianam", "evag", "frankl"],
        dislikes_list: ["alice123", "bobsmith"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "dianam",
        title: "Music Video Premiere",
        description: "Check out the premiere of the new music video!",
        spotify_link: "",
        image_url: "https://example.com/image4.jpg",
        likes_list: ["alice123", "charlieb", "evag"],
        dislikes_list: ["bobsmith", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "evag",
        title: "Musician Spotlight",
        description: "Highlighting a talented musician and their journey.",
        spotify_link: "",
        image_url: "https://example.com/image5.jpg",
        likes_list: ["bobsmith", "dianam", "frankl"],
        dislikes_list: ["alice123", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "frankl",
        title: "Music Production Tips",
        description: "Sharing some tips for music producers!",
        spotify_link: "",
        image_url: "https://example.com/image6.jpg",
        likes_list: ["charlieb", "evag"],
        dislikes_list: ["alice123", "bobsmith", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "gracew",
        title: "Music Playlist",
        description: "Sharing my favorite music playlist!",
        spotify_link: "",
        image_url: "https://example.com/image7.jpg",
        likes_list: ["dianam", "evag"],
        dislikes_list: ["alice123", "bobsmith", "frankl"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "henryn",
        title: "Musician Collaboration",
        description: "Collaborating with another musician on a new project!",
        spotify_link: "",
        image_url: "https://example.com/image8.jpg",
        likes_list: ["evag"],
        dislikes_list: [],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "isabellal",
        title: "Music Genre Exploration",
        description: "Exploring different music genres and their origins.",
        spotify_link: "",
        image_url: "https://example.com/image9.jpg",
        likes_list: ["alice123", "charlieb"],
        dislikes_list: ["bobsmith", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
    {
        username: "jackr",
        title: "Music Instrument Showcase",
        description: "Showcasing different musical instruments and their sounds.",
        spotify_link: "",
        image_url: "https://example.com/image10.jpg",
        likes_list: ["bobsmith", "dianam", "frankl"],
        dislikes_list: ["alice123", "gracew"],
        comments_list: [],
        date_created: new Date("2024-04-17"),
    },
];

export default postMockData